hostname: https://app.briggsdev.tech/

name: briggs-orchestrator
service:
  name: briggs-orchestrator-service
  type: ClusterIP
  port: 80
ingress:
  name: briggs-orchestrator-ingress
  tlssecret: ingress-tls
  className: "nginx"
  hosts:
    - "app.briggsdev.tech"
namespace: briggs-orchestrator

imageTag: development
containerRegistry: briggswalkerdevacr.azurecr.io/briggs-orchestrator-dev

#RequestMemory: "600Mi"
#RequestCPU: "50m"
#LimitMemory: "700Mi"
#LimitCPU: "100m"

