hostname: https://app.briggsdev.tech/

name: briggs-admin-ochestrator
service:
  name: briggs-admin-ochestrator-service
  type: ClusterIP
  port: 80
ingress:
  name: briggs-admin-ochestrator-ingress
  tlssecret: ingress-tls
  className: "nginx"
  hosts:
    - "app.briggsdev.tech"
namespace: briggs-admin-ochestrator

imageTag: development
containerRegistry: briggswalkerdevacr.azurecr.io/briggs-admin-ochestrator-dev

#RequestMemory: "600Mi"
#RequestCPU: "50m"
#LimitMemory: "700Mi"
#LimitCPU: "100m"

